/** User-facing strings. Every line follows docs/design/04-copy-tone-guide.md. */
import type { EnergyLevel } from '../domain/model';

export const copy = {
  appName: 'Become Who You Are',
  energyQuestion: 'How much force have you got right now?',
  energyLabels: { high: 'plenty', medium: 'some', low: 'not much', fried: 'fried' } as Record<EnergyLevel, string>,
  friedNote: 'Then today is autopilot day. Only the light things are showing.',

  firstStepLabel: 'First step',
  /** The first-step test's "without" arm shows only the task. */
  holdoutLabel: 'Just the task, this time',
  firstStepHint: 'Do only this. Then tap the button.',
  energyNow: (level: string) => `Force right now: ${level}.`,
  change: 'change',
  undo: 'Undo',
  quickAdd: {
    button: 'Quick add',
    title: 'Get it out of your head.',
    done: 'done',
    close: 'Close quick add',
  },
  hintDismiss: 'got it',
  hintInfo: "What's this?",
  hints: {
    energy: 'Your answer decides which tasks show up. Low force means only the light ones.',
    mic: 'Tap the mic and say several things at once. Each becomes its own task.',
    rename: 'Tap the task name to fix a typo or a misheard word.',
    also_here: 'Tap any of these to do it now, rename it, or let it go.',
    plan: 'Pick one kind of "when". Plans tied to a moment get done more often.',
    undo: 'Mistapped? Undo is there for a few seconds after anything you might regret.',
    set_aside: 'Nothing here is gone. "bring back" puts it on your list again.',
  } as Record<import('../domain/hints').HintId, string>,
  didIt: 'I did it',
  tooBig: 'still too big',
  notNow: 'not now',
  anotherStep: 'another step',
  editStep: 'in my words',
  save: 'save',
  cancel: 'cancel',

  started: 'Started.',
  keepGoing: 'Keep going',
  thatCounts: 'That counts. Stop here.',
  pickUp: 'Pick up where you left off.',
  done: 'Done',
  doneFlash: 'Done.',
  completions: ['Imposed on the world.', 'That exists now because of you.', 'One less weight.'],

  slipTitle: 'This one keeps slipping.',
  slipBody: "That often means it's built wrong, not that you are. Shrink it, or let it go?",
  reshapeTitle: 'This might need a different shape.',
  reshapeBody: "Smaller didn't help, so size isn't the problem. Put the first step in your own words, or let it go?",
  shrink: 'shrink it',
  letGo: 'let it go',
  itsFine: "it's fine",
  released: 'Released. Looking away is allowed.',

  capturePlaceholder: "Dump it here. Don't sort it.",
  captured: 'Captured. First step ready.',
  voiceStart: 'Talk instead of typing',
  voiceStop: 'Done talking',
  voiceListening: 'Listening. Say it all, in any order.',
  voiceTapToStop: 'Tap the mic again when you are done.',
  voiceKeyboard: "This browser can't listen. Type it instead.",
  voiceCaught: (n: number) => (n === 1 ? 'Caught it. First step ready.' : `Caught ${n} things. Each has a first step.`),
  voiceMissed: "Didn't catch that. Try again, or type it.",
  alsoHere: 'Also here',
  rowHint: 'Shows: do this now, rename, let it go',
  doNow: 'do this now',
  rename: 'rename',
  renameHint: 'tap to rename',
  heldBack: (n: number) => `${n} heavier ${n === 1 ? 'thing is' : 'things are'} resting until you have more force.`,

  feeds: (statement: string) => `feeds ${statement}`,
  becomingLink: 'Becoming',
  nowLink: 'Now',

  onboarding: {
    camelTitle: "Dump everything you're carrying.",
    camelBody: "Talk or type. One thing per line. Don't sort it.",
    talk: 'Talk',
    doneTalking: 'Done talking',
    camelPlaceholder: 'email the landlord\ntaxes\ncall mom\nthat thing about the car',
    lionTitle: 'Some of that was handed to you.',
    lionBody: 'Which of it do you actually want?',
    keep: 'keep',
    notMine: 'not mine',
    notNowShort: 'not now',
    childTitle: 'Who are you becoming?',
    childBody: 'Not a goal. A person.',
    childExamples: ['someone who writes every week', "a dad who's actually in the room", 'someone whose home feels like a home'],
    childSkip: "I don't know yet",
    childSkipNote: "You don't have to know yet.",
    amorTitle: 'Your brain works differently.',
    amorBody:
      'It has real costs. Many people with a brain like this also report upsides: deep absorption when something grabs them, a gear that kicks in under a deadline, a hunger for the new. This app is built for the brain you have.',
    optInTitle: 'One more thing.',
    optInBody:
      'Now and then, should the app ask whether a routine still deserves a place in your life? One question, easy to skip. You can turn it off anytime.',
    optInYes: 'Yes',
    optInNo: 'Not now',
    next: 'Continue',
    skip: 'skip',
  },

  recurrence: {
    question: 'If you had to live this day again, innumerable times, exactly the same, would you keep this on the list?',
    yes: 'Yes, again',
    no: 'No',
    unsure: 'not sure',
    skip: 'skip',
    close: 'close',
    noTitle: "Then let's question it.",
    reshape: 'Reshape it',
    rarer: 'Make it rarer',
    toll: "It's a toll",
    letGo: 'Let it go',
    keep: 'Keep it anyway',
    betterDay: 'Ask me again on a better day',
    reshapeTitle: "What would a version you'd say yes to look like?",
    tollTitle: "This one's a toll, not a choice.",
    tollBody: 'Some things are the price of a life you want. Could this one weigh less?',
    lowerBar: 'Lower the bar',
    tollFine: "It's fine as is",
    unsureTitle: 'Fair.',
    unsureBody: 'Want to look at it closer, or ask me again next week?',
    lookCloser: 'Look closer',
    nextWeek: 'Next week',
    keptNote: 'Your call. It stays.',
    rarerNote: 'Looser now. See how it feels.',
    tollNote: "Marked as a toll. You won't be asked if it should exist.",
    linkTitle: 'Who does this make you?',
    mostlyNo: "That's a lot of no. That's important information, not a crisis. Look at the bigger picture in Becoming sometime.",
    frequencyTitle: "You've skipped this a few times.",
    frequencyBody: 'Ask less often, or not at all?',
    less: 'Less often',
    off: 'Not at all',
    same: 'Keep asking',
  },

  becoming: {
    title: 'Who are you becoming?',
    empty: "You don't have to know yet.",
    addPlaceholder: 'someone who…',
    add: 'add',
    outgrow: "I've outgrown this",
    authored: (a: number, t: number) => `${a} of ${t} routines are ones you'd live again.`,
    authoredTitle: 'Your list, authored.',
    routines: 'Routines',
    routinePlaceholder: 'a walk, morning pages, call mom…',
    cadence: { daily: 'daily', few_per_week: 'few times a week', weekly: 'weekly', monthly: 'monthly' } as Record<string, string>,
    standing: {
      affirmed: "you'd live it again",
      questioned: 'questioned',
      reshaping: 'reshaping',
      unasked: 'not asked yet',
    } as Record<string, string>,
    tollLabel: 'a toll',
    released: 'Set aside',
    releasedEmpty: 'Nothing set aside. Letting go is a skill too.',
    releasedNote: 'Nothing here is lost. Bring anything back with one tap.',
    restingTag: 'for later',
    releasedTag: 'let go',
    bringBack: 'bring back',
    broughtBack: 'Back on your list.',
    hintsSetting: 'Show small hints the first time you see something',
    testSetting: 'Test whether first steps help me',
    testNote: "Half of the tasks you add will show only the task, no first step. Once there are 20 starts, you'll see which way got you going sooner. Stop anytime.",
    testProgress: (n: number, need: number) => `${n} of ${need} starts so far.`,
    testResult: (withStep: string, without: string, a: number, b: number) =>
      `With a first step you started in ${withStep}. Without one: ${without}. From ${a} and ${b} starts, so treat it as a hint, not a verdict.`,
    testSame: (a: number, b: number) => `No clear difference yet, from ${a} and ${b} starts.`,
    hintsReset: 'show them all again',
    hintsResetDone: 'Hints will show again as you go.',
    recurrenceSetting: 'Now and then, ask if a routine still deserves its place',
    nudgesSetting: 'Send gentle notifications',
    nudgesNote: 'Only at times you plan, plus one daily nudge if you want it. Never more than six a day.',
    nudgesDenied: 'Android is blocking notifications for this app. You can allow them in the system settings.',
    dailyLabel: 'One daily nudge about something that has sat a while',
    dailyOff: 'none',
    dailyTimes: ['09:00', '12:00', '17:00', '20:00'],
    aphorism: { text: 'You shall become the person you are.', source: 'The Gay Science §270' },
  },

  plan: {
    link: 'plan when',
    change: 'change plan',
    title: 'When will you do it?',
    body: 'Tie it to something that already happens. A plan with a when and a where gets done more often than a good intention alone.',
    modes: { event: 'a moment', after: 'after a task', time: 'a time' } as Record<'event' | 'after' | 'time', string>,
    addPlace: 'add a place or a stall plan',
    when: 'When…',
    whenPlaceholder: 'I finish my coffee',
    after: 'Right after…',
    where: 'Where (optional)',
    wherePlaceholder: 'at my desk',
    stall: 'plan for a stall',
    ifLabel: 'If I…',
    ifPlaceholder: 'pick up my phone instead',
    thenLabel: "then I'll…",
    thenPlaceholder: 'put it face down and do the first step',
    save: 'set the plan',
    remove: 'remove plan',
    saved: 'Planned. Go live until then.',
    readBackTitle: 'Say it to yourself once.',
    readBackDone: 'said it',
    waiting: 'Waiting for their moment',
    itsNow: "it's now",
    firedHeader: 'You planned this.',
    slipOption: 'plan a when',
    atTime: 'At…',
    timePlaceholder: '9:30pm',
    timeHelp: 'Try something like 9:30pm or 21:30.',
    willAsk: "I'll ask Android for permission to send one notification at that time.",
  },

  settings: {
    title: 'Settings',
    link: 'Settings',
    appearance: 'Appearance',
    lightSetting: 'Light mode',
    lightNote: 'Dark is the default. This choice stays on this device.',
    guidance: 'Guidance',
    notifications: 'Notifications',
    experiments: 'Experiments',
    org: 'Org-mode',
    orgSetting: (file: string) => `Keep ${file} in the sync folder`,
    orgNote: 'Optional, for Emacs or Orgzly. Change a keyword, retitle something, rewrite a FIRST_STEP or add a heading there, and it comes back here on the next sync.',
    orgNeedsSync: 'Set up sync first. The .org file lives in the same WebDAV folder.',
    orgNoteGpg: 'Emacs opens it with your key (EasyPG) and encrypts it to the same key when you save. Orgzly can\'t read .gpg files.',
    orgNeedsKey: 'With encryption on, the Org file is written only as .org.gpg. Import a GPG key below to turn it on.',
  },

  crypto: {
    title: 'Encryption',
    off: 'Off. Whoever runs the WebDAV server can read your synced data.',
    on: 'On. The server only ever sees scrambled data. Use the same passphrase on every device.',
    needsSync: 'Set up sync first.',
    turnOn: 'encrypt',
    change: 'change passphrase',
    passphrase: 'Passphrase',
    passphraseNote: "The passphrase is never stored or synced. If you forget it, your devices keep everything, but you'll have to replace what's on the server.",
    working: 'Unlocking… this takes a few seconds.',
    done: 'Done. Every other device will ask for this passphrase.',
    wrong: "That passphrase doesn't open the synced data.",
    replace: "replace the server's copy with this device's",
    replaceNote: "Only if the passphrase is lost: anything synced from other devices that isn't on this one yet is gone.",
    failed: "That didn't work. The reason is above.",
    gpgTitle: 'GPG key for Org',
    gpgNone: 'Paste a key and the Org file becomes .org.gpg, encrypted to it, so Emacs opens it with your own keyring.',
    gpgPaste: 'Paste the output of gpg --armor --export (or --export-secret-keys)',
    gpgPassphrase: "The key's passphrase, if it's a protected secret key",
    gpgImport: 'import key',
    gpgRemove: 'remove key',
    gpgWorking: 'Reading the key…',
    gpgKey: (who: string, fpr: string) => `${who} · ${fpr}`,
    gpgTwoWay: 'Secret key imported: edits made in Emacs come back here.',
    gpgOneWay: "Public key only: the app writes .org.gpg, but can't read edits made in Emacs. Import the secret key on a device where you want them back.",
    gpgStored: 'The key stays on this device (in this browser, on the web) and is never synced. Consider a separate key or subkey just for this.',
  },

  sync: {
    title: 'Sync',
    off: 'Keep your phone and the web version in step through a WebDAV folder (Nextcloud, Fastmail, rclone, any WebDAV server).',
    waiting: 'Sync is on.',
    syncing: 'Syncing…',
    syncedAt: (time: string) => `Synced at ${time}.`,
    setUp: 'set up sync',
    edit: 'change',
    now: 'sync now',
    stop: 'stop syncing',
    save: 'save and sync',
    url: 'WebDAV folder',
    urlPlaceholder: 'https://cloud.example.com/remote.php/dav/files/you/become/',
    user: 'Username',
    password: 'Password or app password',
    note: 'Use an app password if your server offers one. It stays on this device and is never synced.',
  },

  evidence: {
    title: 'Look at you now.',
    noted: 'noted',
    section: 'Evidence',
    empty: "Proof that you're getting faster shows up here once there's enough of it to be true. Nothing here is made up.",
  },

  emptyNow: "Nothing here. Either you're done, or you're about to capture something. Both are good.",
  aphorism: {
    text: 'One must still have chaos in oneself to be able to give birth to a dancing star.',
    source: 'Thus Spoke Zarathustra, Prologue §5',
  },
};

export function completionLine(seed: number): string {
  return copy.completions[Math.abs(seed) % copy.completions.length];
}
